
package com.master.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "Service", targetNamespace = "http://service.master.com/")
@XmlSeeAlso({ ObjectFactory.class })
public interface Service {


    /**
     *
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://service.master.com/",
                    className = "com.master.service.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://service.master.com/",
                     className = "com.master.service.HelloResponse")
    @Action(input = "http://service.master.com/Service/helloRequest",
            output = "http://service.master.com/Service/helloResponse")
    public String hello(@WebParam(name = "name", targetNamespace = "") String name);

    /**
     *
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "Contact")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Contact", targetNamespace = "http://service.master.com/",
                    className = "com.master.service.Contact")
    @ResponseWrapper(localName = "ContactResponse", targetNamespace = "http://service.master.com/",
                     className = "com.master.service.ContactResponse")
    @Action(input = "http://service.master.com/Service/ContactRequest",
            output = "http://service.master.com/Service/ContactResponse")
    public Boolean contact();

}
