package com.master.service;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.1.3.0.0.1008
public class ServicePortClient {
    public static void main(String[] args) {
        Service_Service service_Service = new Service_Service();
        Service service = service_Service.getServicePort();
        // Add your code to call the desired methods.


    }
}
